# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
backend/requirement/api/docs/swagger.yaml:
  info-license:
    - '#/info'
  tag-description:
    - '#/tags/0/description'
    - '#/tags/1/description'
    - '#/tags/2/description'
    - '#/tags/3/description'
    - '#/tags/4/description'
    - '#/tags/5/description'
    - '#/tags/6/description'
  operation-operationId:
    - '#/paths/~1auth~1register/post/operationId'
    - '#/paths/~1auth~1login/post/operationId'
    - '#/paths/~1users/get/operationId'
    - '#/paths/~1users/post/operationId'
    - '#/paths/~1users~1count/get/operationId'
    - '#/paths/~1users~1{id}/get/operationId'
    - '#/paths/~1users~1{id}/put/operationId'
    - '#/paths/~1users~1{id}/delete/operationId'
    - '#/paths/~1challenges/get/operationId'
    - '#/paths/~1challenges/post/operationId'
    - '#/paths/~1challenges~1count/get/operationId'
    - '#/paths/~1challenges~1{virtualId}/get/operationId'
    - '#/paths/~1challenges~1{virtualId}/put/operationId'
    - '#/paths/~1challenges~1{virtualId}/delete/operationId'
    - '#/paths/~1challenges~1{virtualId}/patch/operationId'
    - '#/paths/~1ideas/get/operationId'
    - '#/paths/~1ideas/post/operationId'
    - '#/paths/~1ideas~1count/get/operationId'
    - '#/paths/~1ideas~1{virtualId}/get/operationId'
    - '#/paths/~1ideas~1{virtualId}/put/operationId'
    - '#/paths/~1ideas~1{virtualId}/delete/operationId'
    - '#/paths/~1comments/get/operationId'
    - '#/paths/~1comments/post/operationId'
    - '#/paths/~1comments~1count/get/operationId'
    - '#/paths/~1comments~1{id}/get/operationId'
    - '#/paths/~1comments~1{id}/put/operationId'
    - '#/paths/~1comments~1{id}/delete/operationId'
    - '#/paths/~1activities/get/operationId'
    - '#/paths/~1activities/post/operationId'
    - '#/paths/~1activities~1count/get/operationId'
    - '#/paths/~1activities~1{id}/get/operationId'
    - '#/paths/~1activities~1{id}/put/operationId'
    - '#/paths/~1activities~1{id}/delete/operationId'
    - '#/paths/~1notifications/get/operationId'
    - '#/paths/~1notifications/post/operationId'
    - '#/paths/~1notifications~1count/get/operationId'
    - '#/paths/~1notifications~1{id}/get/operationId'
    - '#/paths/~1notifications~1{id}/put/operationId'
    - '#/paths/~1notifications~1{id}/delete/operationId'
    - '#/paths/~1notifications~1{id}/patch/operationId'
  operation-4xx-response:
    - '#/paths/~1users/get/responses'
    - '#/paths/~1users/post/responses'
    - '#/paths/~1users~1count/get/responses'
    - '#/paths/~1users~1{id}/get/responses'
    - '#/paths/~1users~1{id}/put/responses'
    - '#/paths/~1users~1{id}/delete/responses'
    - '#/paths/~1challenges/get/responses'
    - '#/paths/~1challenges/post/responses'
    - '#/paths/~1challenges~1count/get/responses'
    - '#/paths/~1challenges~1{virtualId}/get/responses'
    - '#/paths/~1challenges~1{virtualId}/put/responses'
    - '#/paths/~1challenges~1{virtualId}/delete/responses'
    - '#/paths/~1challenges~1{virtualId}/patch/responses'
    - '#/paths/~1ideas/get/responses'
    - '#/paths/~1ideas/post/responses'
    - '#/paths/~1ideas~1count/get/responses'
    - '#/paths/~1ideas~1{virtualId}/get/responses'
    - '#/paths/~1ideas~1{virtualId}/put/responses'
    - '#/paths/~1ideas~1{virtualId}/delete/responses'
    - '#/paths/~1comments/get/responses'
    - '#/paths/~1comments/post/responses'
    - '#/paths/~1comments~1count/get/responses'
    - '#/paths/~1comments~1{id}/get/responses'
    - '#/paths/~1comments~1{id}/put/responses'
    - '#/paths/~1comments~1{id}/delete/responses'
    - '#/paths/~1activities/get/responses'
    - '#/paths/~1activities/post/responses'
    - '#/paths/~1activities~1count/get/responses'
    - '#/paths/~1activities~1{id}/get/responses'
    - '#/paths/~1activities~1{id}/put/responses'
    - '#/paths/~1activities~1{id}/delete/responses'
    - '#/paths/~1notifications/get/responses'
    - '#/paths/~1notifications/post/responses'
    - '#/paths/~1notifications~1count/get/responses'
    - '#/paths/~1notifications~1{id}/get/responses'
    - '#/paths/~1notifications~1{id}/put/responses'
    - '#/paths/~1notifications~1{id}/delete/responses'
    - '#/paths/~1notifications~1{id}/patch/responses'
  security-defined:
    - '#/paths/~1auth~1register/post'
    - '#/paths/~1auth~1login/post'
    - '#/paths/~1users/get'
    - '#/paths/~1users/post'
    - '#/paths/~1users~1count/get'
    - '#/paths/~1users~1{id}/get'
    - '#/paths/~1users~1{id}/put'
    - '#/paths/~1users~1{id}/delete'
    - '#/paths/~1challenges/get'
    - '#/paths/~1challenges/post'
    - '#/paths/~1challenges~1count/get'
    - '#/paths/~1challenges~1{virtualId}/get'
    - '#/paths/~1challenges~1{virtualId}/put'
    - '#/paths/~1challenges~1{virtualId}/delete'
    - '#/paths/~1challenges~1{virtualId}/patch'
    - '#/paths/~1challenges~1{virtualId}~1upvote/post'
    - '#/paths/~1challenges~1{virtualId}~1subscribe/post'
    - '#/paths/~1ideas/get'
    - '#/paths/~1ideas/post'
    - '#/paths/~1ideas~1count/get'
    - '#/paths/~1ideas~1{virtualId}/get'
    - '#/paths/~1ideas~1{virtualId}/put'
    - '#/paths/~1ideas~1{virtualId}/delete'
    - '#/paths/~1ideas~1{virtualId}~1upvote/post'
    - '#/paths/~1ideas~1{virtualId}~1subscribe/post'
    - '#/paths/~1comments/get'
    - '#/paths/~1comments/post'
    - '#/paths/~1comments~1count/get'
    - '#/paths/~1comments~1{id}/get'
    - '#/paths/~1comments~1{id}/put'
    - '#/paths/~1comments~1{id}/delete'
    - '#/paths/~1activities/get'
    - '#/paths/~1activities/post'
    - '#/paths/~1activities~1count/get'
    - '#/paths/~1activities~1{id}/get'
    - '#/paths/~1activities~1{id}/put'
    - '#/paths/~1activities~1{id}/delete'
    - '#/paths/~1notifications/get'
    - '#/paths/~1notifications/post'
    - '#/paths/~1notifications~1count/get'
    - '#/paths/~1notifications~1{id}/get'
    - '#/paths/~1notifications~1{id}/put'
    - '#/paths/~1notifications~1{id}/delete'
    - '#/paths/~1notifications~1{id}/patch'
